---
toc: true
---

# Welcome {.unnumbered}

::: {.callout-note}
## Registrations for the 2024 session are closed.

Registrations open each spring and the training course takes place during the fall. 

{{< fa hand-point-right >}}&nbsp; Subscribe to the 
[FRB-CESAB newsletter](https://www.fondationbiodiversite.fr/en/newsletter/) 
to stay informed. More information is available on the [FRB-CESAB website](https://www.fondationbiodiversite.fr/en/the-frb-in-action/programs-and-projects/le-cesab/develop-skills/la_donnee_en_biodiversite/).
:::



This five-day training course, co-organized by the [FRB-CESAB](https://www.fondationbiodiversite.fr/en/about-the-foundation/le-cesab/), the [PNDB](https://www.pndb.fr/), and [GBIF France](http://www.gbif.fr/) aims to work on the different stages of the data cycle, from acquisition to opening, including management, storage and the drafting of data papers.

We will 1) contextualize the issues surrounding the understanding, sharing and (re)use of biodiversity data and metadata, and 2) enhance the skills of communities involved in one or more stages of the data cycle.



## Program {.unnumbered}

**General context**

- Current challenges in biodiversity data
- The data ecosystem
- Reproducibility concepts
- What is data/metadata?
- Major types of biodiversity data
- Framework and good practices (data cycle, FAIR, etc.)

**Data acquisition**

- Best practices for data collection
- Major biodiversity databases
- Data acquisition: Web portals, API & web scraping

**Data management**

- Structure, formats & files
- Processing & cleansing data
- OpenRefine
- Virtual Research Environments

**DataSHARE projects**

- FRB-CESAB DataSHARE call
- Zoom on Islets & PhenoFish groups

**Legal aspects**

- Sharing, licensing, etc.

**Opening data**

- Data management plan
- (Meta)data: standards
- Storage and archiving
- Dissemination and sharing
- Enhancing value: data paper & software paper


## Prerequisites {.unnumbered}

{{< fa hand-point-right >}}&nbsp; Please follow this [tutorial](https://frbcesab.github.io/rsetup/) to install 
your working environment **before attending the training course**. Note that you just need to install [R](https://cran.r-project.org/), [RStudio IDE](https://posit.co/download/rstudio-desktop/) (optional) and [Rtools](https://cran.r-project.org/bin/windows/Rtools/) (for Windows users).


## Material {.unnumbered}

All the material used in this training course (slides, data, exercises) is available at: <https://github.com/biodiversitydata/>



## Citation {.unnumbered}

> Casajus N, Coux C, Le Bras Y, Norvez O, Archambeau A-S  & Pamerlon S (2024) Biodiversity data: From data collection to publication. An FRB-CESAB, PNDB & GBIF France training course. URL: <https://biodiversitydata.github.io/>


## Contributions {.unnumbered}

If you see mistakes or want to suggest changes, please [create an issue](https://github.com/biodiversitydata/biodiversitydata.github.io/issues/new) on the source repository.


## Reuse {.unnumbered}

Text and figures are licensed under Creative Commons Attribution [CC By 4.0](https://creativecommons.org/licenses/by/4.0/), unless otherwise noted.


## See also {.unnumbered}


Discover the other training courses provided by the FRB-CESAB and its partners: <https://frbcesab.github.io/training-courses/>


